# Generated by Django 5.2.7 on 2025-10-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=255)),
                ('BookDescription', models.CharField(max_length=10000)),
            ],
        ),
    ]
