apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  #namespace: book-rental
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: postgres-storage