
apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: book-rental
  #namespace: django-cluster # Match with namespace
  name: django # MARK C
  labels:
    app: django # MARK C
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django # MARK C
  template:
    metadata:
      labels:
        app: django # MARK C
    spec:
      containers:
      - name: django
        image: ghcr.io/sw-code/book-rental-py:main #django-immage #hypercorn_deb_false_db_5432
        ports:
        - containerPort: 8000 # MARK C.1
        imagePullPolicy: Always
      restartPolicy: Always


