apiVersion: v1
kind: PersistentVolume
metadata:
   name: postgres-storage # MARK Z
   #namespace: book-rental # Must match with namespace.
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /tmp/TestVolume

