on:
  workflow_run:
    workflows: ["Docker"]
    types: [requested]

jobs:    
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Azure
    steps:
      - uses: actions/checkout@v5
      - name: Make the script files executable
        run: chmod +x start.sh stop.sh

      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - run: |
          ./stop.sh
          ./start.sh

      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_S_TEST }}
        with:
          args: get pods -n prod

